# Generated by Django 5.1.5 on 2025-02-05 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brandprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('seeker', 'Brand/Business'), ('influencer', 'Influencer'), ('brand', 'Brand')], default='seeker', max_length=15),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencerprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
