# Generated by Django 5.1.5 on 2025-02-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_influencerprofile_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerprofile',
            name='metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
