# Generated by Django 5.1.5 on 2025-02-04 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='influencermetric',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='campaignmetric',
            unique_together={('campaign', 'metric_type', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='contentmetric',
            unique_together={('content', 'metric_type', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='influencermetric',
            unique_together={('influencer', 'metric_type', 'platform', 'timestamp')},
        ),
    ]
