# Generated by Django 5.1.5 on 2025-02-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationpreference_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={},
        ),
    ]
